export const popularBreedsKo: { key: string; label: string }[] = [
  { key: 'pomeranian', label: '포메라니안' },
  { key: 'maltese', label: '말티즈' },
  { key: 'poodle/standard', label: '푸들' },
  { key: 'chihuahua', label: '치와와' },
  { key: 'shiba', label: '시바견' },
  { key: 'retriever/golden', label: '골든 리트리버' },
  { key: 'beagle', label: '비글' },
  { key: '믹스견', label: '믹스견' },
  { key: '기타', label: '기타' },
];

export const dogBreedLabelsKo: Record<string, string> = {
  pomeranian: '포메라니안',
  maltese: '말티즈',
  'poodle/standard': '푸들',
  'poodle/toy': '토이 푸들',
  'poodle/miniature': '미니어처 푸들',
  chihuahua: '치와와',
  shiba: '시바견',
  'retriever/golden': '골든 리트리버',
  'retriever/chesapeake': '체서피크 베이 리트리버',
  'retriever/flatcoated': '플랫코티드 리트리버',
  'retriever/curly': '컬리코티드 리트리버',
  beagle: '비글',
  'bulldog/french': '프렌치 불독',
  'bulldog/english': '잉글리시 불독',
  'bulldog/boston': '보스턴 테리어',
  dachshund: '닥스훈트',
  corgi: '코기',
  'corgi/cardigan': '카디건 웰시 코기',
  'corgi/pembroke': '펨브로크 웰시 코기',
  husky: '허스키',
  'terrier/yorkshire': '요크셔 테리어',
  'terrier/westhighland': '웨스트 하이랜드 화이트 테리어',
  'terrier/scottish': '스코티시 테리어',
  'terrier/border': '보더 콜리',
  collie: '콜리',
  'collie/border': '보더 콜리',
  dalmatian: '달마시안',
  doberman: '도베르만',
  'german/shepherd': '독일 셰퍼드',
  akita: '아키타',
  'spaniel/cocker': '코커 스파니엘',
  'spaniel/brittany': '브리타니 스파니엘',
  pug: '퍼그',
  samoyed: '사모예드',
  'pointer/german': '저먼 포인터',
  whippet: '휘핏',
  greyhound: '그레이하운드',
  'hound/blood': '블러드하운드',
  'hound/basset': '바셋하운드',
  'hound/afghan': '아프간 하운드',
  'hound/ibizan': '이비잔 하운드',
  'hound/plott': '플롯 하운드',
  'hound/walker': '워커 하운드',
  'spitz/japanese': '재패니즈 스피츠',
  'spitz/indian': '인디언 스피츠',
  'sheepdog/shetland': '셰틀랜드 쉽독',
  'sheepdog/english': '잉글리시 쉽독',
  'sheepdog/australian': '오스트레일리안 쉽독',
  'sheepdog/border': '보더 콜리',
  'sheepdog/oldenglish': '올드 잉글리시 쉽독',
  'sheepdog/scottish': '스코티시 쉽독',
  'labrador/retriever': '래브라도 리트리버',
  '믹스견': '믹스견',
  '기타': '기타',
};
