const { withDangerousMod } = require('expo/config-plugins');
const fs = require('fs');
const os = require('os');
const path = require('path');

function expandHome(value) {
  if (!value) return value;
  if (value.startsWith('~/')) return path.join(os.homedir(), value.slice(2));
  if (value.startsWith('~')) return path.join(os.homedir(), value.slice(1));
  return value.replace(/\$HOME/g, os.homedir());
}

function resolveAndroidSdkPath() {
  const fromEnv = expandHome(
    process.env.ANDROID_SDK_PATH ??
      process.env.ANDROID_HOME ??
      process.env.ANDROID_SDK_ROOT,
  );
  if (fromEnv) return fromEnv;

  throw new Error(
    'Android SDK 경로가 설정되지 않았습니다. .env 에 ANDROID_SDK_PATH=$HOME/Library/Android/sdk 를 추가하세요.',
  );
}

/** Gradle용 sdk.dir 값 (Windows 백슬래시 이스케이프) */
function toGradleSdkDir(sdkPath) {
  return sdkPath.replace(/\\/g, '\\\\');
}

/** @type {import('expo/config-plugins').ConfigPlugin} */
const withAndroidLocalProperties = (config) =>
  withDangerousMod(config, [
    'android',
    async (modConfig) => {
      const sdkPath = resolveAndroidSdkPath();
      const localPropertiesPath = path.join(
        modConfig.modRequest.platformProjectRoot,
        'local.properties',
      );

      fs.writeFileSync(
        localPropertiesPath,
        `## Auto-generated by plugins/withAndroidLocalProperties.js — do not commit\nsdk.dir=${toGradleSdkDir(sdkPath)}\n`,
      );

      return modConfig;
    },
  ]);

module.exports = withAndroidLocalProperties;
